name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  makromusic_button: 
    git:
      url: https://github.com/makromusic/flutter_tutorials
      ref: cf8d3a66a3b506b07d0dbeb3e8fe45979912643c
      path: makromusic_button

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
