name: makromusic_button
description: "A simple Flutter button widget with a makromusic logo!"
version: 0.0.1
homepage: https://makromusic.com
repository: https://github.com/makromusic/flutter_tutorials/tree/main/makromusic_button

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
   assets:
     - lib/assets/
